### ISSUE TITLE
ModuleNotFoundError:

### ISSUE THREAD

**Issue by Chinna111** [nityansuman/automated-test-platform#1]
(base) C:\Users\Elavarasan\Marvin-AI-master>runserver.py
Traceback (most recent call last):
  File "C:\Users\Elavarasan\Marvin-AI-master\runserver.py", line 6, in <module>
    from marvin_ai import app
  File "C:\Users\Elavarasan\Marvin-AI-master\marvin_ai\__init__.py", line 5, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

**Comment by nityansuman** [comment]
Have fixed the issues. Update the project. @Chinna111 
Better re-clone it. Then run "pip3 install -r requirements.txt" in the project environment.

**Comment by LeninPrakash41** [comment]
I have the updated code but still I got an error saying ModuleNotFoundError: No module named 'marvin_ai'. I also tried installing marvin_ai from github as well as using pip install marvin-python-toolbox but no luck.

**Comment by nityansuman** [comment]
Error Fixed. @LeninPrakash41
